name: æ‰“åŒ…é¡¹ç›®
on:
  workflow_dispatch:
    inputs:
        build:
            description: 'é€‰æ‹©è¦æ„å»ºçš„æ–‡ä»¶ç¼–å·'
            required: true
            default: 'true'
permissions:
  contents: write
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: è¯»å–ä»“åº“
        uses: actions/checkout@v4
      - name: è®¾ç½® Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: å®‰è£…ä¾èµ–
        run: |
          cd 01-base/base-01
          npm install

      - name: æ‰“åŒ…
        run: |
          cd 01-base/base-01
          npm run build
      - name: ä¸Šä¼  Artifacts ğŸ”º
        uses: actions/upload-artifact@v1
        with:
          name: 01-build
          path: 01-build

  deploy:
    concurrency: ci-${{ github.ref }}
    needs: [build] # The second job must depend on the first one to complete before running and uses ubuntu-latest instead of windows.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: ä¸‹è½½ Artifacts ğŸ”» # The built project is downloaded into the 'site' folder.
        uses: actions/download-artifact@v4
        with:
          name: 01-build

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: '01-build'
