name: æ‰“åŒ…é¡¹ç›®
on:
  workflow_dispatch:
    inputs:
        build:
            description: 'é€‰æ‹©è¦æ„å»ºçš„æ–‡ä»¶ç¼–å·'
            required: true
            default: 'true'
permissions:
  contents: write
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: è¯»å–ä»“åº“
        uses: actions/checkout@v4
      - name: è®¾ç½® Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Install rsync ğŸ“š
        run: |
          choco install rsync
      - name: å®‰è£…ä¾èµ–
        run: |
          cd 01-base/base-01
          npm install

      - name: æ‰“åŒ…
        run: |
          cd 01-base/base-01
          npm run build
      - name: éƒ¨ç½² ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: 01-build
          folder: 01-build
      - name: ä¸Šä¼ 
        uses: actions/upload-artifact@v4
        with:
          name: 01-build
          path: 01-build
